django/api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path('', WebinarHome.as_view(), name="home"),
    path('create-webinar/', CreateWebinar.as_view()),
    path('list-webinar/<int:pk>/', SpecificWebinar.as_view()),
    path('create-booking/<int:pk>/', CreateBooking.as_view()),
    path('all-bookings/', AllBooking.as_view()),
    path('login/', LoginView.as_view()),
    path('up-vote/<int:web_id>/', UpVoteView.as_view()),
    path('down-vote/<int:web_id>/', DownVoteView.as_view()),
    path('test/', test),
    path('linkedin-oauth2/callback/', LinkedInView.as_view())
    # path('linkedin/', LinkedInView.as_view())
]

django/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('webinar/<str:webinar_id>/', webinar, name='webinar'),
    path('book-webinar/<str:webinar_id>/', book_webinar, name='booking'),
    path('booking/', all_bookings, name='all_bookings'),
    path('up-vote/', up_vote_webinar, name='up_vote'),
    path('down-vote/', down_vote_webinar, name='down_vote')
]

django/refier/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('api/', include('api.urls', namespace='api')),
]

django/main/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    profile = models.OneToOneField(User, on_delete=models.CASCADE)
    host = models.BooleanField(default=False)
    mobile = models.CharField(max_length=10)

    def __str__(self):
        return self.profile.username


class Webinar(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    sub_heading = models.CharField(max_length=100, blank=True, null=True, verbose_name='Sub Heading')
    description = models.TextField(null=True, blank=True)
    instructor = models.CharField(max_length=30, verbose_name='Instructor Name')
    event_on = models.DateTimeField()
    cost = models.CharField(max_length=5, default=0)
    up_vote = models.IntegerField(default=0)
    down_vote = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Webinars'

    def __str__(self):
        return self.title


class Booking(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    event = models.ForeignKey(Webinar, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    email = models.EmailField()
    mobile = models.CharField(max_length=10)

    class Meta:
        verbose_name_plural = 'Bookings'

    def __str__(self):
        return f'{self.name} - {self.event}'

django/main/forms.py
from django import forms
from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        exclude = ['event']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'})
        }

django/main/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .forms import BookingForm
from .models import Webinar, Booking


def home(request):
    """home page for all webinars"""
    return render(
        request,
        'main/home.html',
        {
            'title': 'All Webinars',
            'free_web': Webinar.objects.filter(cost='0').order_by('event_on'),
            'premium': Webinar.objects.exclude(cost='0').order_by('event_on')
        }
    )


def webinar(request, webinar_id):
    """webinar view page"""
    return render(
        request,
        'main/webinar.html',
        {
            'title': 'Webinar',
            'webinar': Webinar.objects.get(id=webinar_id),
        }
    )


def book_webinar(request, webinar_id):
    """book webinar page"""
    form = BookingForm(request.POST or None)
    webinar_ins = Webinar.objects.get(id=webinar_id)

    if form.is_valid():
        form.instance.event = webinar_ins
        form.save()
        messages.add_message(request, messages.SUCCESS, 'WEBINAR SUCCESSFULLY BOOKED')
        return redirect('main:home')

    return render(
        request,
        'main/book_webinar.html',
        {
            'title': 'Booking Page',
            'webinar': webinar_ins,
            'form': form
        }
    )


def all_bookings(request):
    """page for viewing all bookings"""
    return render(
        request,
        'main/bookings.html',
        {
            'title': 'All Booking',
            'bookings': Booking.objects.all()[:25]
        }
    )


def up_vote_webinar(request):
    """route for up_vote a webinar"""
    if request.method == 'POST':
        webinar_ins = Webinar.objects.get(id=request.POST.get('id'))
        webinar_ins.up_vote += 1
        webinar_ins.save()

        return JsonResponse({'up_vote': webinar_ins.up_vote})


def down_vote_webinar(request):
    """route for down_vote a webinar"""
    if request.method == 'POST':
        webinar_ins = Webinar.objects.get(id=request.POST.get('id'))
        webinar_ins.down_vote += 1
        webinar_ins.save()

        return JsonResponse({'down_vote': webinar_ins.down_vote})

django/templates/main/book_webinar.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container-fluid"
     style="display: flex; flex-direction: column; height: 90vh; justify-content: center; align-items: center;">
    <h3>WEBINAR: {{webinar.title}}</h3>
    <h5>ON: {{webinar.event_on}}</h5>
    <div class="p-3" style="width: 500px;">
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit" class="btn btn-primary w-100">
                {% if webinar.cost == '0' %}
                    Book Now
                {% else %}
                    Pay {{ webinar.cost }} Now
                {% endif %}
            </button>
        </form>
    </div>
</div>
{% endblock %}

django/templates/main/bookings.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container" style="margin-top: 4rem;">
    {% if bookings %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Booked On</th>
                    <th scope="col">Name</th>
                    <th scope="col">Webinar</th>
                    <th scope="col">Event On</th>
                </tr>
            </thead>
            <tbody>
                {% for booking in bookings %}
                <tr>
                    <th scope="row">{{ booking.created }}</th>
                    <td>{{ booking.name }}</td>
                    <td>{{ booking.event.title }}</td>
                    <td>{{ booking.event.event_on }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h4>No Bookings!!</h4>
    {% endif %}
</div>
{% endblock %}

django/templates/main/home.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container-fluid mt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert" style="width: fit-content; margin: auto;">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <h1 class="text-muted fw-bolder">Upcoming Free Events</h1>
    <div class="row">
        {% for free in free_web %}
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card my-3">
                <h4 class="card-header">{{ free.title }}</h4>
                <div class="card-body">
                    {% if free.sub_heading %}
                    <h5 class="card-title">{{ free.sub_heading }}</h5>
                    {% endif %}
                    <p class="card-text"
                       style="height: 100px; overflow: hidden; text-align: justify;">
                        {{ free.description }}
                    </p>
                    <div class="card-text d-flex flex-row justify-content-between fw-bold">
                        <div>{{ free.event_on.date }}</div>
                        <div>{{ free.event_on.time }}</div>
                    </div>
                    <div class="card-text d-flex flex-row justify-content-between fw-bold py-2">
                        <div>{{ free.instructor }}</div>
                        <div>Free</div>
                    </div>
                    <div class="card-footer d-flex flex-row justify-content-between">
                        <a href="{% url 'main:webinar' free.id %}" class="btn btn-primary">CLICK TO KNOW MORE</a>
                        <div class="card-text d-flex flex-row">
                            <div class="mx-2">
                                <i class="bi bi-hand-thumbs-up" style="cursor: pointer" data-id="{{ free.id }}"
                                   onclick="upVote(this)"></i>
                                <span>{{ free.up_vote }}</span>
                            </div>
                            <div class="mx-2">
                                <i class="bi bi-hand-thumbs-down" style="cursor: pointer" data-id="{{ free.id }}"
                                   onclick="downVote(this)"></i>
                                <span>{{ free.down_vote }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
            <h4>No Upcoming Free Events</h4>
        {% endfor %}
    </div>

    <h1 class="text-muted fw-bolder">Upcoming Premium Events</h1>
    <div class="row">
        {% for pre in premium %}
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card my-3">
                <h4 class="card-header">{{ pre.title }}</h4>
                <div class="card-body">
                    {% if pre.sub_heading %}
                    <h5 class="card-title">{{ pre.sub_heading }}</h5>
                    {% endif %}


                    <p class="card-text"
                       style="height: 100px; overflow: hidden; text-align: justify">
                        {% if pre.description %}
                        {{ pre.description }}
                        {% else %}
                        No description available!!
                        {% endif %}
                    </p>

                    <div class="card-text d-flex flex-row justify-content-between fw-bold">
                        <div>{{ pre.event_on.date }}</div>
                        <div>{{ pre.event_on.time }}</div>
                    </div>
                    <div class="card-text d-flex flex-row justify-content-between fw-bold py-2">
                        <div>{{ pre.instructor }}</div>
                        <div>{{ pre.cost }}</div>
                    </div>
                    <div class="card-footer d-flex flex-row justify-content-between">
                        <a href="{% url 'main:webinar' pre.id %}" class="btn btn-primary">CLICK TO KNOW MORE</a>
                        <div class="card-text d-flex flex-row">
                            <div class="mx-2">
                                <i class="bi bi-hand-thumbs-up" style="cursor: pointer" data-id="{{ pre.id }}"
                                   onclick="upVote(this)"></i>
                                <span>{{ pre.up_vote }}</span>
                            </div>
                            <div class="mx-2">
                                <i class="bi bi-hand-thumbs-down" style="cursor: pointer" data-id="{{ pre.id }}"
                                   onclick="downVote(this)"></i>
                                <span>{{ pre.down_vote }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
            <h4>No Upcoming Premium Events</h4>
        {% endfor %}
    </div>
</div>
{% endblock %}

django/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <title>{{ title }}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}">Refier-Task</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
            <ul class="navbar-nav ml-4">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'main:all_bookings' %}">Bookings</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>

{% block script %}
{% endblock %}
</body>
</html>

django/templates/main/webinar.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card text-light bg-dark" style="width: 50%; margin: calc((100%/2) - 33%) auto; min-height: 400px;">
        <div class="card-body lh-lg">
            <h2 class="card-text fw-bolder">{{ webinar.title }}</h2>
            {% if webinar.sub_heading %}
            <div class="card-subheader fs-3">{{ webinar.sub_heading }}</div>
            {% endif %}
            <div class="card-text">
                <i class="bi bi-calendar-week"></i>
                {{ webinar.event_on.date }}
            </div>
            <div class="card-text">
                <i class="bi bi-alarm"></i>
                {{ webinar.event_on.time }}
            </div>
            <div class="card-text">Rs.
                {% if webinar.cost == '0' %}
                    Free
                {% else %}
                    {{ webinar.cost }}
                {% endif %}
            </div>
            <div class="card-text">{{ webinar.instructor }}</div>
            <div class="card-text d-flex flex-row">
                <div class="mx-2">
                    <i class="bi bi-hand-thumbs-up" style="cursor: pointer" data-id="{{ webinar.id }}"
                       onclick="upVote(this)"></i>
                    <span>{{ webinar.up_vote }}</span>
                </div>
                <div class="mx-2">
                    <i class="bi bi-hand-thumbs-down" style="cursor: pointer" data-id="{{ webinar.id }}"
                                   onclick="downVote(this)"></i>
                    <span>{{ webinar.down_vote }}</span>
                </div>
            </div>
            <a href="{% url 'main:booking' webinar.id %}">
                <button class="btn btn-warning p-3 mt-2 border-0 rounded-pill">
                    Book Your Seat
                </button>
            </a>
        </div>
    </div>
</div>
{% endblock %}